# Generated by Django 5.0.6 on 2024-06-03 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0002_delete_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='notedate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 3, 24, 32, 322936)),
        ),
        migrations.AddField(
            model_name='note',
            name='notename',
            field=models.CharField(default='t', max_length=100),
        ),
    ]
