# Generated by Django 5.0.6 on 2024-06-03 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0004_alter_note_notedate_alter_note_notename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='notedate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 19, 9, 13, 382031)),
        ),
    ]
