# Generated by Django 5.0.6 on 2024-06-03 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0005_alter_note_notedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='moded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='notedate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 20, 56, 9, 601384)),
        ),
    ]
