# Generated by Django 5.0.6 on 2024-06-03 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0006_note_moded_alter_note_notedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='notedate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 22, 17, 45, 741271)),
        ),
    ]
