# Generated by Django 5.0.6 on 2024-06-04 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0009_alter_note_notedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='notedate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 3, 5, 56, 259467)),
        ),
    ]
